export enum StreamState {
    NOT_INITIALIZED ="NOT_INITIALIZED",
    INITIALIZED ="INITIALIZED",
    STOPPED="STOPPED",
    NOT_FOUND="NOT_FOUND",
    AWAITING="AWAITING",
    NOT_PUBLISHED="NOT_PUBLISHED",
    UNKNOWN="UNKNOWN",
    UNPUBLISHED="UNPUBLISHED",
    PUBLISHED="PUBLISHED",
    CLOSED="CLOSED",
    ERROR="ERROR"
}
