import {Logger} from "../logger/Logger";
import {StormPlayerCore} from "../StormPlayerCore";

/**
 * Saves and retrieve data from localStorage.
 */
export class StorageManager {

    /**
     * Decides whenever logs are being generated by this class
     * @private
     */
    private readonly LOG_ACTIVITY: boolean = false;

    /**
     * Whenever saving cookies is enabled at all
     * @private
     */
    private isEnabled:boolean = true;

    /**
     * Prefix for multiple instances
     * @private
     */
    private prefix:string = "";

    /**
     * Reference to the main logger
     * @private
     */
    private logger:Logger;

    /**
     * Constructor
     * @param main
     * @param prefix
     */
    constructor(main: StormPlayerCore) {

        this.logger = main.getLogger();
        this.isEnabled = main.getConfigManager()?.getSettingsData()?.getStorageData().enabled ?? this.isEnabled;
        this.prefix = main.getConfigManager()?.getSettingsData()?.getStorageData().prefix ?? this.prefix;

        if(this.LOG_ACTIVITY)
            this.logger.info(this, "Creating new StorageManager");

    }

    /**
     * Saves data a a cookie
     * @param name name of a field
     * @param value value of a field
     */
    public saveField(name:string, value:string):void {

        if(this.isEnabled == true) {
            if (this.LOG_ACTIVITY)
                this.logger.info(this, "Saving data: " + name + " | " + value);

            localStorage.setItem(this.prefix+name, value);
        }

    }

    /**
     * Retrieves field from cookie
     * @param name cookie name
     */
    public getField(name:string):string|null {

        if(this.isEnabled == true) {

            const value: string | null = localStorage.getItem(this.prefix + name);

            if (this.LOG_ACTIVITY)
                this.logger.info(this, "Grabbing data: " + name + " | " + value);

            return value;
        } else
            return null;

    }

}